#!/bin/bash

export PROJECTNAME="."

# TO DO : test $PROJECTNAME
echo "the project location is : $PROJECTNAME"
echo "removing libs"
vdel -lib $PROJECTNAME/LIB/LIB_AES -all
vdel -lib $PROJECTNAME/LIB/LIB_RTL -all
vdel -lib $PROJECTNAME/LIB/LIB_BENCH -all

echo "creating library "
vlib $PROJECTNAME/LIB/LIB_AES
vmap LIB_AES $PROJECTNAME/LIB/LIB_AES
vlib $PROJECTNAME/LIB/LIB_RTL
vmap LIB_RTL $PROJECTNAME/LIB/LIB_RTL
vlib $PROJECTNAME/LIB/LIB_BENCH
vmap LIB_BENCH $PROJECTNAME/LIB/LIB_BENCH

echo "compile third party library"
vcom -work LIB_AES $PROJECTNAME/SRC/PACKAGE/state_definition_package.vhd

echo "compile vhdl sources"
vcom -work LIB_RTL $PROJECTNAME/SRC/RTL/Counter.vhd
vcom -work LIB_RTL $PROJECTNAME/SRC/RTL/KeyExpansion_table.vhd
#A compléter
vcom -work LIB_RTL $PROJECTNAME/SRC/RTL/Sbox.vhd
vcom -work LIB_RTL $PROJECTNAME/SRC/RTL/SubBytes.vhd
vcom -work LIB_RTL $PROJECTNAME/SRC/RTL/ShiftRow.vhd
vcom -work LIB_RTL $PROJECTNAME/SRC/RTL/MixColumn.vhd
vcom -work LIB_RTL $PROJECTNAME/SRC/RTL/addRoundKey.vhd
vcom -work LIB_RTL $PROJECTNAME/SRC/RTL/AES.vhd
vcom -work LIB_RTL $PROJECTNAME/SRC/RTL/AES_Round.vhd
vcom -work LIB_RTL $PROJECTNAME/SRC/RTL/AES_FSM.vhd
vcom -work LIB_RTL $PROJECTNAME/SRC/RTL/MUX.vhd



echo "compile vhdl test bench"
vcom -work LIB_BENCH $PROJECTNAME/SRC/BENCH/Counter_tb.vhd
vcom -work LIB_BENCH $PROJECTNAME/SRC/BENCH/Sbox_tb.vhd
vcom -work LIB_BENCH $PROJECTNAME/SRC/BENCH/SubBytes_tb.vhd
vcom -work LIB_BENCH $PROJECTNAME/SRC/BENCH/ShiftRows_tb.vhd
vcom -work LIB_BENCH $PROJECTNAME/SRC/BENCH/addRoundKey_tb.vhd
vcom -work LIB_BENCH $PROJECTNAME/SRC/BENCH/MixColumn_tb.vhd
vcom -work LIB_BENCH $PROJECTNAME/SRC/BENCH/KeyExpansion_table_tb.vhd
vcom -work LIB_BENCH $PROJECTNAME/SRC/BENCH/AES_tb.vhd
vcom -work LIB_BENCH $PROJECTNAME/SRC/BENCH/AES_Round_tb.vhd



echo "compilation finished"

echo "start simulation..."
# ATTENTION un seul VSIM decommenté à la fois!
# vsim .


